
name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8.0.0

      - name: Set up Python
        run: uv python install 3.14

      - name: Install just
        run: uv tool install rust-just

      - name: Install dependencies
        run: uv sync

      - name: Run linters
        run: just lint

      - name: Check types
        run: just typing

      - name: Run pytest
        run: just test

      - name: Generate test coverage
        run: just cov
